version: '3.9'
services:
  core:
    container_name: "core"
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env/local.env
    
  esearch:
    container_name: search
    image: elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    
